version: 2
updates:

  # Maintain dependencies for Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Zurich"
    assignees:
      - "coorasse"
    labels:
      - "dep-update"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "bundler"
      include: "scope"
